import 'package:flutter/material.dart';
import '../../features/category/domain/entities/category_entity.dart';

List<CategoryEntity> getDefaultCategories(String userId) {
  return [
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      // Pass userId when adding to DB
      name: "Food & Dining",
      colorHex: "#9C27B0",
      // purpleAccent approximate hex
      message: "Good food is the key to a good mood!\nEnjoy every meal with happiness.",
      iconCodePoint: Icons.fastfood.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Groceries",
      colorHex: "#4CAF50",
      message: "Stocking up on essentials for a better tomorrow!\nGroceries for the win.",
      iconCodePoint: Icons.local_grocery_store.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Health & Wellness",
      colorHex: "#F44336",
      message: "Your health is wealth.\nStay strong, stay healthy, keep thriving.",
      iconCodePoint: Icons.local_hospital.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Transport & Travel",
      colorHex: "#2196F3",
      message: "Journey towards new experiences.\nTravel well, and enjoy every moment!",
      iconCodePoint: Icons.directions_bus.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Shopping",
      colorHex: "#FF9800",
      message: "From fashion to essentials,\nyour shopping spree was a hit!",
      iconCodePoint: Icons.shopping_cart.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Bills & Utilities",
      colorHex: "#F44336",
      message: "Paying bills is a necessity,\nkeeping the lights on and the water flowing.",
      iconCodePoint: Icons.receipt.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Entertainment & Leisure",
      colorHex: "#FFC107",
      message: "Life's too short for boredom!\nEnjoy your favorite shows and activities.",
      iconCodePoint: Icons.movie.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Education",
      colorHex: "#03A9F4",
      message: "Learning is the gateway to success.\nYour education expenses are investments in the future.",
      iconCodePoint: Icons.school.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Savings & Investments",
      colorHex: "#009688",
      message: "Every penny saved is a step towards financial freedom.\nKeep investing in your future!",
      iconCodePoint: Icons.savings.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Income",
      colorHex: "#4CAF50",
      message: "Hard work pays off.\nYour income is the result of your dedication.",
      iconCodePoint: Icons.attach_money.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Gifts & Donations",
      colorHex: "#E91E63",
      message: "Sharing is caring.\nYour gifts and donations spread happiness and love.",
      iconCodePoint: Icons.card_giftcard.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Insurance",
      colorHex: "#673AB7",
      message: "Peace of mind comes with good coverage.\nYour insurance keeps you protected.",
      iconCodePoint: Icons.security.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Household & Rent",
      colorHex: "#795548",
      message: "Home is where the heart is.\nYour household and rent expenses keep your sanctuary intact.",
      iconCodePoint: Icons.home.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Business & Work Expenses",
      colorHex: "#3F51B5",
      message: "Your business is growing!\nThese expenses ensure your professional success.",
      iconCodePoint: Icons.business.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Miscellaneous",
      colorHex: "#9E9E9E",
      message: "Life is full of surprises.\nYour miscellaneous expenses keep things interesting!",
      iconCodePoint: Icons.category.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "EMI & Loan Repayments",
      colorHex: "#FF5722",
      message: "Paying off debts one step at a time.\nYour EMI payments are a journey to financial freedom.",
      iconCodePoint: Icons.account_balance_wallet.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "Borrowed Money",
      colorHex: "#F44336",
      message: "Borrowed but not forgotten.\nKeep track of your borrowings and manage them well.",
      iconCodePoint: Icons.money_off.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
    CategoryEntity(
      id: UniqueKey().toString(),
      userId: userId,
      name: "ATM / Debt",
      colorHex: "#607D8B",
      message: "ATMs and debt can sometimes be a burden,\nbut you're on your way to clearing them!",
      iconCodePoint: Icons.local_atm.codePoint,
      iconFontFamily: 'MaterialIcons',
      iconFontPackage: null,
    ),
  ];
}