// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlE4R9TsnJ-NTI1e7REKx4AlS1jW4CG0',
    appId: '1:802538147467:web:a63287295b0932b7dc4e8e',
    messagingSenderId: '802538147467',
    projectId: 'personal-money-managemen-a23ec',
    authDomain: 'personal-money-managemen-a23ec.firebaseapp.com',
    storageBucket: 'personal-money-managemen-a23ec.firebasestorage.app',
    measurementId: 'G-5BPX6CVZ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGosfR9erdVKxs2IhhEwlBXZHCvGIoad8',
    appId: '1:802538147467:android:a90c2d0de3364663dc4e8e',
    messagingSenderId: '802538147467',
    projectId: 'personal-money-managemen-a23ec',
    storageBucket: 'personal-money-managemen-a23ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFiloPnh474Pn8R_M5TjB2zNrmDkb1wHY',
    appId: '1:802538147467:ios:5f6e06e77e1c67c4dc4e8e',
    messagingSenderId: '802538147467',
    projectId: 'personal-money-managemen-a23ec',
    storageBucket: 'personal-money-managemen-a23ec.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFiloPnh474Pn8R_M5TjB2zNrmDkb1wHY',
    appId: '1:802538147467:ios:5f6e06e77e1c67c4dc4e8e',
    messagingSenderId: '802538147467',
    projectId: 'personal-money-managemen-a23ec',
    storageBucket: 'personal-money-managemen-a23ec.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlE4R9TsnJ-NTI1e7REKx4AlS1jW4CG0',
    appId: '1:802538147467:web:3a0d851953d5ff09dc4e8e',
    messagingSenderId: '802538147467',
    projectId: 'personal-money-managemen-a23ec',
    authDomain: 'personal-money-managemen-a23ec.firebaseapp.com',
    storageBucket: 'personal-money-managemen-a23ec.firebasestorage.app',
    measurementId: 'G-ZFKF5H2ZWQ',
  );
}
